### ISSUE TITLE
https://github.com/JakubAndrysek/mkdocs-typedoc/blob/main/typedoc/plugin.py

### ISSUE THREAD

**Issue by Cotswoldsmaker** [JakubAndrysek/mkdocs-typedoc#4]
Unfortunately, when you run your code with `mkdocs serve` in a poetry env, the output directory is way off. For example, I put 
```
  - typedoc:
      source: ../src/**/*.ts
      output_dir: docs/ts-code
      tsconfig: ../tsconfig.json
```
in my mkdocs.yml config file and  the output is more like in 

`[info] html generated at /var/folders/1_/fzs51vf175984x440fxf6byr0000gn/T/mkdocs_9s0pgfiu/docs/ts-code`

when it should be 

`~/github/a_repo/docs/mkdocs.yml`

I think a small amount of refactoring might be needed.
